### ISSUE TITLE
DockerFIle had a cp target 

### ISSUE THREAD

**Issue by 87utierrez** [edwin/hello-world-java-docker#1]
Your docker had a cp target/*.jar  but in your GitHub repo you do not have a target folder, can you explain?

**Comment by edwin** [comment]
hi @87utierrez 
you need to run maven build first in order to generate `target` folder

```
$ mvn clean package
```

**Comment by 87utierrez** [comment]
Ok, Thank you! Question ???
have you deploy docker file running java to openshift or K8S

**Comment by edwin** [comment]
hi @87utierrez 
yes, ive tried before also documenting it on below blog post
```
https://edwin.baculsoft.com/2020/07/building-containerized-images-on-openshift-4-and-push-the-result-to-third-party-image-registry/
```
